### PR TITLE
Using fetch for post request

### PR DESCRIPTION
**Pull request by dDenysS**

### CODE REVIEW

**Comment by MachinisteWeb** [comment]
Hello Den, there is no `then` part in this example if you want produce the exact same behavior has before. So the correct code should be only:

```
fetch(<url>, { method: "POST", body: <data> });
```

Why do not do the same for GET ?!

What about others `$.ajax` usage accross all others part of the file?!

I wil update that.

**Comment by dDenysS** [comment]
Hello Haeresis. I will update the file in all other parts

**Comment by MachinisteWeb** [comment]
Thx a lot, you will find here the way we want do that.

EXAMPLE:

#### POST ####

From jQuery

```js
$.ajax({
  type: 'POST',
  url: <url>,
  data: <data>
});
```

to Vanilla JS

```js
fetch(<url>, {
  method: 'POST',
  body: <data>
});

/* // IE fallback
var post = new XMLHttpRequest();
post.open('POST', <url>, true);
post.setRequestHeader('Content-Type', 'application/x-www-form-urlencoded; charset=UTF-8');
post.send(<data>); */
```

**Comment by dDenysS** [comment]
Оk.I will continue to do the same as you have shown

**Pull request merged**
